name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # o il branch principale del tuo repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Esegui lo script Bash per aggiornare la versione
      - name: Update version indicator
        run: |
          chmod +x update-version.sh
          ./update-version.sh

      # Configura Git e committa le modifiche (se ci sono)
      - name: Commit version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update version to $(git rev-parse --short HEAD) (build $(date '+%d/%m/%Y %H:%M:%S'))" || echo "No changes to commit"

      # Deploy su GitHub Pages (usa un'azione dedicata)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # o il percorso della cartella da pubblicare
